/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StaySafeGame {
    }
}
declare global {
    interface HTMLStaySafeGameElement extends Components.StaySafeGame, HTMLStencilElement {
    }
    var HTMLStaySafeGameElement: {
        prototype: HTMLStaySafeGameElement;
        new (): HTMLStaySafeGameElement;
    };
    interface HTMLElementTagNameMap {
        "stay-safe-game": HTMLStaySafeGameElement;
    }
}
declare namespace LocalJSX {
    interface StaySafeGame {
    }
    interface IntrinsicElements {
        "stay-safe-game": StaySafeGame;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stay-safe-game": LocalJSX.StaySafeGame & JSXBase.HTMLAttributes<HTMLStaySafeGameElement>;
        }
    }
}
