/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LandingPage {
    }
    interface StaySafeGame {
        "level": number;
        "loseEvent": Function;
        "winEvent": Function;
    }
    interface StaySafeLauncher {
    }
}
declare global {
    interface HTMLLandingPageElement extends Components.LandingPage, HTMLStencilElement {
    }
    var HTMLLandingPageElement: {
        prototype: HTMLLandingPageElement;
        new (): HTMLLandingPageElement;
    };
    interface HTMLStaySafeGameElement extends Components.StaySafeGame, HTMLStencilElement {
    }
    var HTMLStaySafeGameElement: {
        prototype: HTMLStaySafeGameElement;
        new (): HTMLStaySafeGameElement;
    };
    interface HTMLStaySafeLauncherElement extends Components.StaySafeLauncher, HTMLStencilElement {
    }
    var HTMLStaySafeLauncherElement: {
        prototype: HTMLStaySafeLauncherElement;
        new (): HTMLStaySafeLauncherElement;
    };
    interface HTMLElementTagNameMap {
        "landing-page": HTMLLandingPageElement;
        "stay-safe-game": HTMLStaySafeGameElement;
        "stay-safe-launcher": HTMLStaySafeLauncherElement;
    }
}
declare namespace LocalJSX {
    interface LandingPage {
    }
    interface StaySafeGame {
        "level"?: number;
        "loseEvent"?: Function;
        "winEvent"?: Function;
    }
    interface StaySafeLauncher {
    }
    interface IntrinsicElements {
        "landing-page": LandingPage;
        "stay-safe-game": StaySafeGame;
        "stay-safe-launcher": StaySafeLauncher;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "landing-page": LocalJSX.LandingPage & JSXBase.HTMLAttributes<HTMLLandingPageElement>;
            "stay-safe-game": LocalJSX.StaySafeGame & JSXBase.HTMLAttributes<HTMLStaySafeGameElement>;
            "stay-safe-launcher": LocalJSX.StaySafeLauncher & JSXBase.HTMLAttributes<HTMLStaySafeLauncherElement>;
        }
    }
}
